language: python
env:
  global:
    - CI=true
# addons:
#   apt_packages:
#     - pandoc
# command to install dependencies

matrix:
  include:
    - os: linux
      python: 3.5
    
    - os: osx
      sudo: required
      language: generic
      
#  Manually install python on osx
before-install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then

      brew update;
      brew install python3;
      
  else
      # Install some custom requirements on Linux
  fi
  
install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then

      python3 -m venv venv;
      source venv/bin/activate;
      pip install . test
      
  else
      pip install . test
  fi
script: python tests/supervisor.py
branches:
  only:
    - master