language: python
python:
  - "3.5"
env:
  global:
    - CI=true
# addons:
#   apt_packages:
#     - pandoc
# command to install dependencies
os:
  - linux
  # Evidently this doesn't work?
  # - osx
install:
  - pip install . test
script: python tests/supervisor.py
branches:
  only:
    - master