language: python
env:
  global:
    - CI=true
# addons:
#   apt_packages:
#     - pandoc
# command to install dependencies

matrix:
  include:
    - os: linux
      python: 3.5
    
    - os: osx
      sudo: required
      language: generic
      
before-install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then

      git clone https://github.com/MacPython/terryfy
      source terryfy/travis_tools.sh
      get_python_environment  macpython 3.5.2
      
  else
      # Install some custom requirements on Linux
  fi
  
install:
  - pip install . test
script: python tests/supervisor.py
branches:
  only:
    - master