language: python
python:
  - "3.5"
env:
  global:
    - CI=true
# addons:
#   apt_packages:
#     - pandoc
# command to install dependencies

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.5
    
    - os: osx
      sudo: required
      language: generic
  
install:
  - .travis-install.sh
  - pip install . test
script: python tests/supervisor.py
branches:
  only:
    - master